In [2]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**PART 1: CUSTOM DATASET**

In [25]:
import pandas as pd

# Dataset dictionary
data = {
    "Name": ["Selam", "Hana", "Selamawit", "Sara", "Musa",
             "Liya", "Daniel", "Hana", "Kebede", "Abele",
             "Ali", "Ruth", "Abebe", "Tigist", "Meseret"],

    "Age": [22, 34, 29, 41, 19,
            25, 37, 28, 45, 31,
            23, 27, 36, 24, 40],

    "Gender": ["F", "M", "M", "F", "M",
               "F", "M", "F", "M", "F",
               "M", "F", "M", "F", "M"],

    "Department": ["IT", "HR", "Finance", "IT", "Marketing",
                   "HR", "Finance", "IT", "HR", "Marketing",
                   "IT", "Finance", "HR", "Marketing", "IT"],

    "Salary": [50000, 60000, 55000, 70000, 45000,
               52000, 62000, 68000, 58000, 72000,
               51000, 63000, 59000, 71000, 65000]
}

# Custom index
index = [f"EMP_{i:02d}" for i in range(1, 16)]

# Create DataFrame
df_custom = pd.DataFrame(data, index=index)

print(" Custom Dataset ")
df_custom

 Custom Dataset

             Name  Age Gender Department  Salary
EMP_01      Selam   22      F         IT   50000
EMP_02       Hana   34      M         HR   60000
EMP_03  Selamawit   29      M    Finance   55000
EMP_04       Sara   41      F         IT   70000
EMP_05       Musa   19      M  Marketing   45000
EMP_06       Liya   25      F         HR   52000
EMP_07     Daniel   37      M    Finance   62000
EMP_08       Hana   28      F         IT   68000
EMP_09     Kebede   45      M         HR   58000
EMP_10      Abele   31      F  Marketing   72000
EMP_11        Ali   23      M         IT   51000
EMP_12       Ruth   27      F    Finance   63000
EMP_13      Abebe   36      M         HR   59000
EMP_14     Tigist   24      F  Marketing   71000
EMP_15    Meseret   40      M         IT   65000

**PART 2: TITANIC DATASET**

In [6]:
file_path = "/content/drive/MyDrive/train.csv"

titanic = pd.read_csv(file_path)

**STEP 1: EXPLORATION**

In [17]:
print(" HEAD ")
titanic.head()

 HEAD

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Middle
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult

In [12]:
print(" INFO ")
titanic.info()

 INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  AgeGroup     714 non-null    category
dtypes: category(1), float64(2), int64(5), object(5)
memory usage: 84.7+ KB

In [13]:
print(" DESCRIBE ")
titanic.describe()

 DESCRIBE

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

**STEP 2: DATA CLEANING**

In [36]:
# Fill missing Age with median
titanic["Age"].fillna(titanic["Age"].median(), inplace=True)

# Fill missing Embarked with mode
titanic["Embarked"].fillna(titanic["Embarked"].mode()[0], inplace=True)

# Drop Cabin column
titanic.drop(columns=["Cabin"], inplace=True, errors = "ignore")

# Remove duplicates
titanic.drop_duplicates(inplace=True)

# Check remaining missing values
titanic.isnull().sum()

/tmp/ipykernel_399/2144795810.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic["Age"].fillna(titanic["Age"].median(), inplace=True)
/tmp/ipykernel_399/2144795810.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic["Embarked"].fillna(titanic["Embarked"].mode()[0], inplace=True)

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
AgeGroup       0
dtype: int64

**STEP 3: DATA ANALYSIS (GROUPBY)**

*1, Survival rate by gender*

In [31]:
gender_survival = titanic.groupby("Sex")["Survived"].mean()
gender_survival

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

*2, Survival rate by class*

In [32]:
class_survival = titanic.groupby("Pclass")["Survived"].mean()
class_survival

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

*3, Average age per class*

In [33]:
avg_age = titanic.groupby("Pclass")["Age"].mean()
avg_age

Pclass
1    36.812130
2    29.765380
3    25.932627
Name: Age, dtype: float64

*4. Survival rate by age group*

In [34]:
titanic["AgeGroup"] = pd.cut(
    titanic["Age"],
    bins=[0, 12, 18, 35, 60, 100],
    labels=["Child", "Teen", "Adult", "Middle", "Senior"]
)

age_survival = titanic.groupby("AgeGroup")["Survived"].mean()
age_survival

/tmp/ipykernel_399/2958533762.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  age_survival = titanic.groupby("AgeGroup")["Survived"].mean()

AgeGroup
Child     0.579710
Teen      0.428571
Adult     0.353271
Middle    0.400000
Senior    0.227273
Name: Survived, dtype: float64

**STEP 4: FILTERING**

*Female survivors*

In [10]:
female_survivors = titanic[(titanic["Sex"] == "female") & (titanic["Survived"] == 1)]
female_survivors.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Middle
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Adult
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Teen

*Children survivors*

In [14]:
children_survivors = titanic[(titanic["Age"] < 18) & (titanic["Survived"] == 1)]
children_survivors.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeGroup
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Teen
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,Child
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q,Teen
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C,Teen
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C,Child

*1st class passengers survival rate*

In [16]:
first_class_survival = titanic[titanic["Pclass"] == 1]["Survived"].mean()
print("First Class Survival Rate:", first_class_survival)

First Class Survival Rate: 0.6296296296296297

**STEP 5: INSIGHTS**

1. Who was more likely to survive? (Gender)

>> Females were more likely to survive than males.

The survival rate for female passengers was significantly higher.
This reflects the historical evacuation policy of “women and children first.”

2. Did class affect survival?

>> Yes, passenger class had a strong impact on survival.

1st class passengers had the highest survival rate.

3rd class passengers had the lowest survival rate.

This indicates that socio-economic status influenced survival chances, as higher-class passengers had better access to lifeboats and safer locations.

3. Were children prioritized?

>> Yes, children were prioritized during evacuation.

Children had a higher survival rate compared to many adult groups.
This suggests that vulnerable passengers were given priority.

4. What combination had the highest survival rate?

>> Female passengers in 1st class had the highest survival probability.

This shows that survival was influenced by a combination of factors:

Gender (female)
Class (1st class)
Age (younger passengers)

**Final Insight**

Survival on the Titanic was not random — it was strongly influenced by social hierarchy, gender-based priority, and age, with female first-class passengers having the highest chance of survival.